name: Auto Pull Request
run-name: PR by ${{ github.actor }}

on:
  push:
    branches:
      - feat/**

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pull_request:
    if: ${{ !contains(github.event.head_commit.message, 'Merge branch') }}
    name: Create Pull Action
    runs-on: ubuntu-latest
    steps:
      - name: Check Repo
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: vsoch/pull-request-action@1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: qa
          PULL_REQUEST_TITLE: "Auto PR: ${{ github.ref_name }} to qa"
          PULL_REQUEST_BODY: | 
            ## Razon de PR:
            "${{ github.event.head_commit.message }}"

            ## Autor:
            "${{ github.actor }}"            
          # PULL_REQUEST_REVIEWERS: "${{ github.repository_owner }}"
